---
# tasks file for install_docker

- name: Install required dependency packages
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present
    update_cache: true
  become: true

- name: Download Docker GPG key  # noqa: command-instead-of-module
  ansible.builtin.command: >
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  args:
    creates: /etc/apt/keyrings/docker.gpg
  become: true

- name: Add Docker repository to APT sources
  ansible.builtin.apt_repository:
    repo: >
      deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.gpg]
      https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present
    filename: docker
  become: true

- name: Update package index
  ansible.builtin.apt:
    update_cache: true
  become: true

- name: Install Docker and related packages
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
  become: true

- name: Enable Docker service to start on boot
  ansible.builtin.systemd:
    name: docker
    enabled: true
  become: true

- name: Start Docker service
  ansible.builtin.systemd:
    name: docker
    state: started
  become: true


- name: Add User To Docker Group
  ansible.builtin.user:
    name: "{{ ansible_env.USER }}"
    groups: docker
    append: true
  become: true
